In [1]:
import numpy as np

# 생성

In [2]:
np.zeros(2)

array([0., 0.])

In [3]:
np.ones(2)

array([1., 1.])

In [5]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [6]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
np.ones(2, dtype=np.int64)

array([1, 1], dtype=int64)

# 변환

In [28]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [29]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [27]:
c = np.reshape(a, newshape=(1, 6), order='C')
print(c)

[[0 1 2 3 4 5]]


In [31]:
a2 = a[np.newaxis, :]
a2.shape
a2

array([[0, 1, 2, 3, 4, 5]])

In [32]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [33]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [34]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [35]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# 인덱싱 슬라이싱

In [38]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [39]:
print(a[a < 7])

[1 2 3 4 5 6]


In [41]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [42]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [43]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [45]:
five_up = (a > 5) | (a == 5)
print(a)
print(five_up)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [49]:
b = np.nonzero(a < 5)
print(b[0])
print(b[1])

[0 0 0 0]
[0 1 2 3]


In [48]:
list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [51]:
print(a)
print(a[b])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]


In [63]:
print(a) 
not_there = np.nonzero(a == 12)
print(not_there)
print(not_there[0])
print(not_there[1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(array([2], dtype=int64), array([3], dtype=int64))
[2]
[3]


In [66]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
print(a)
arr1 = a[3:8]
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]
[4 5 6 7 8]


In [72]:
a1 = np.array([[1, 1],
               [2, 2]])
print("a1")
print(a1)

a2 = np.array([[3, 3],
               [4, 4]])
print("a2")
print(a2)

print("np.vstack")
print(np.vstack((a1, a2)))
print()
print("np.hstack")
print(np.hstack((a1, a2)))

a1
[[1 1]
 [2 2]]
a2
[[3 3]
 [4 4]]
np.vstack
[[1 1]
 [2 2]
 [3 3]
 [4 4]]

np.hstack
[[1 1 3 3]
 [2 2 4 4]]


In [79]:
x = np.arange(1, 25).reshape(2, 12)
print("x")
print(x)
print()

x1 = np.hsplit(x, 3)
print("np.hsplit 1")
print(x1)
x2 = np.hsplit(x, (3, 4))
print("np.hsplit 2")
print(x2)

x
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]

np.hsplit 1
[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]
np.hsplit 2
[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


# 기능

정렬

In [10]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

결합

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# 데이터 보기

In [17]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [18]:
# 차원
array_example.ndim

3

In [19]:
# 데이터 개수
array_example.size

24

In [20]:
# 데이터 shape
array_example.shape

(3, 2, 4)